apiVersion: v1
kind: Service
metadata:
  name: {{ include "homedns.fullname" . }}
  labels:
    {{- include "homedns.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    {{- include "homedns.selectorLabels" . | nindent 4 }}
