apiVersion: v1
kind: Service
metadata:
  name: {{ include "homedns.fullname" . }}
  labels:
    {{- include "homedns.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.name }}
      protocol: UDP
      name: {{ .Values.service.name }}
  selector:
    {{- include "homedns.selectorLabels" . | nindent 4 }}
  ipFamilies:
    - IPv6
apiVersion: v1
kind: Service
metadata:
  name: {{ include "homedns.fullname" . }}-ipv6
  labels:
    {{- include "homedns.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.name }}
      protocol: UDP
      name: {{ .Values.service.name }}
  selector:
    {{- include "homedns.selectorLabels" . | nindent 4 }}
  ipFamilies:
    - IPv6
