{{- if .Values.clusterSecretStore.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.clusterSecretStore.name }}
spec:
  provider:
    {{- range $key, $value := .Values.clusterSecretStore.provider }}
    {{ $key }}: 
      {{- range $subkey, $subvalue := $value }}
      {{ $subkey }}: {{ $subvalue }}
      {{- end }}
    {{- end }}
  {{- if .Values.clusterSecretStore.secretStoreRef }}
  secretStoreRef:
    name: {{ .Values.clusterSecretStore.secretStoreRef.name }}
  {{- end }}
  {{- end }}
